Add deepfaune
naturalsolutions/ecoSecrets pull request #60
Opened 2024-02-22 18:16 UTC by ophdlv

2024-04-22 09:37 UTC, MathildeNS requested changes
- Missing deepfaune code
- Some cache code to delete

2024-10-01 13:10 UTC, MathildeNS approved these changes

2025-09-22 10:48 UTC, camillemonchicourt commented
Salut, je voulais savoir si cette PR qui intègre DeepFaune dans ecoSecrets est installable ? fonctionnelle ?
Ou si il faut encore y travailler ?

2025-11-26 09:34 UTC, MathildeNS commented
Deprecated PR. Refer to #83

2025-11-26 09:34 UTC, closed without merging